### PR TITLE
Download files using SFTP/FTP instead of HTTP

### PR DESCRIPTION
**Pull request by javanthropus**
This PR fixes issue #24.  It should allow for the configured URL to be used solely for advertising to users' web browsers and similar.

### CODE REVIEW

**Comment by javanthropus** [comment]
It looks like the CI failures are the result of dependency gems that require Ruby 2.0 or later when running under Ruby 1.9.  The test under Ruby 2.0 was successful.

**Comment by luan** [comment]
Hi @javanthropus,

Sorry it took me a while to get to this. Could you rebase now that I fixed `.travis.yml` to get the tests to go green?

Thanks,
Luan

**Comment by javanthropus** [comment]
@luan Thanks for taking a look.

**Comment by csenszike** [comment]
Hi!

I would be really interested in this. Is there any update on this pull request? I want't to be able to upload files to a private folder not published on HTTP and retrieve them in controller.

Thanks!

**Comment by javanthropus** [comment]
@csenszike I'm not sure why this never got merged, but we're not using this functionality where I work anymore.  I can rebase again if @luan is interested, but this would probably be my last attempt to get this PR merged.

**Comment by luan** [comment]
I did the rebase, I'm really sorry it took me so long to get to this. I haven't used this library in years and that makes me forget about it at times.

Anyway, merged and release as 0.3.0. Thanks for the PR @javanthropus

**Comment by csenszike** [comment]
Thank you very much!

2017-04-09 1:41 GMT+02:00 Luan Santos <notifications@github.com>:

**Pull request merged**
